[package]
name = "illium-lurk"
version = "0.1.0"
authors = ["cpacia <ctpacia@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Illium lurk integration"
repository = "https://github.com/project-illium/ilxd/zk/rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fcomm = { path = "../../../lurk-rs/fcomm"}
lurk = { path = "../../../lurk-rs"}
camino = "1.1.6"
tempfile = "3.6.0"
flate2 = "1.0.26"
hex = { version = "0.4.3", features = ["serde"] }
anyhow = "1.0.72"
pasta_curves = { git="https://github.com/lurk-lab/pasta_curves", branch="dev" }
bincode = "1.3"

[patch.crates-io]
# This is needed to ensure halo2curves, which imports pasta-curves, uses the *same* traits in bn256_grumpkin
pasta_curves = { git="https://github.com/lurk-lab/pasta_curves", branch="dev" }

