[package]
name = "proofs"
version = "0.1.0"
authors = ["cpacia <ctpacia@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Illium lurk integration"
repository = "https://github.com/project-illium/ilxd/zk/rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fcomm = { path = "../../../lurk-rs/fcomm"}
lurk = { path = "../../../lurk-rs" }