name: Go and Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.3.0-devel-ubuntu20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y curl wget build-essential pkg-config libssl-dev
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          dpkg-reconfigure --frontend noninteractive tzdata

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: |
          which go
          which gcc
          gcc --version
          ls -l /usr/local/cuda/targets/x86_64-linux/lib/
          export LD_LIBRARY_PATH=/usr/local/cuda/targets/x86_64-linux/lib:${LD_LIBRARY_PATH}
          export CGO_CFLAGS="-I/usr/local/cuda/include"
          export CGO_LDFLAGS="-L/usr/local/cuda/targets/x86_64-linux/lib -lcudart"
          make build VERBOSE=1

      - name: Test
        run: go test -v ./...
