name: Go and Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y curl wget build-essential pkg-config libssl-dev
          sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          sudo dpkg-reconfigure --frontend noninteractive tzdata

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: |
          which go
          which gcc
          gcc --version
          make build VERBOSE=1

      - name: Test
        run: go test -v ./...
