name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.output_step.outputs.upload_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Save upload_url to file
        run: echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt

      - name: Upload upload_url as artifact
        uses: actions/upload-artifact@v2
        with:
          name: upload_url
          path: upload_url.txt

  build_and_upload:
    name: Build and Release for Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: ['386', 'amd64']
        platform: ['linux']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version env
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Print upload_url from build_and_upload job
        run: echo "${{ needs.create_release.outputs.upload_url }}"

      - name: Build Rust bindings
        run: |
          mkdir -p lib
          cd crypto/rust && cargo build --release
          cd ../..
          cp crypto/rust/target/release/libillium_crypto.so lib/

      - name: Compile ilxd and ilxcli for ${{ matrix.platform }} ${{ matrix.goarch }}
        run: |
          sudo apt-get install gcc-multilib  # This is needed for 32-bit compilation on 64-bit machines
          go env
          go build -ldflags="-r ./lib" -o bin/ilxd *.go
          cd cli && go build -ldflags="-r ../lib" -o ../bin/ilxcli

      - name: Zip binaries
        run: |
          zip ilxd-${{ env.VERSION }}-${{ matrix.platform }}_${{ matrix.goarch }}.zip bin/ilxd bin/ilxcli

      - name: Download upload_url artifact
        uses: actions/download-artifact@v2
        with:
          name: upload_url

      - name: Set upload_url from file
        id: get_upload_url
        run: echo "::set-output name=upload_url::$(cat upload_url.txt)"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: ./ilxd-${{ env.VERSION }}-${{ matrix.platform }}_${{ matrix.goarch }}.zip
          asset_name: ilxd-${{ env.VERSION }}-${{ matrix.platform }}_${{ matrix.goarch }}.zip
          asset_content_type: application/zip

